// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLi-_pt-u1TWv8Mxsee_CeuOpKicz4LXE',
    appId: '1:379824293998:web:eb91cba78a804f7fce3e7f',
    messagingSenderId: '379824293998',
    projectId: 'flutter-test-8c8d0',
    authDomain: 'flutter-test-8c8d0.firebaseapp.com',
    storageBucket: 'flutter-test-8c8d0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVYnNRSiFIau2-2Y7NA8V3S_WcKNzkYCI',
    appId: '1:379824293998:android:ce66909fe9360cddce3e7f',
    messagingSenderId: '379824293998',
    projectId: 'flutter-test-8c8d0',
    storageBucket: 'flutter-test-8c8d0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlWlqYZxL9bmt76WRPrJT9nMPne-VNst0',
    appId: '1:379824293998:ios:fb59c5c429faaaf8ce3e7f',
    messagingSenderId: '379824293998',
    projectId: 'flutter-test-8c8d0',
    storageBucket: 'flutter-test-8c8d0.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlWlqYZxL9bmt76WRPrJT9nMPne-VNst0',
    appId: '1:379824293998:ios:fb59c5c429faaaf8ce3e7f',
    messagingSenderId: '379824293998',
    projectId: 'flutter-test-8c8d0',
    storageBucket: 'flutter-test-8c8d0.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );
}
